<?php get_header(); ?> 
<table class="law_table">
  <tr>
    <th>法人名</th>
    <td>Bamboo Brush Art 齊藤龍太郎</td>
  </tr>
  <tr>
    <th>所在地</th>
    <td>千葉県流山市江戸川台東4丁目379番地</td>
</tr>
<tr>
  <th>TEL</th>
  <td>090-2172-2307</td>
</tr>
<tr>
  <th>メールアドレス</th>
  <td>bamboo.brush.art@gmail.com</td>
</tr>
  <tr>
    <th>販売責任者</th>
    <td>齊藤　龍太郎</td>
  </tr>
  <tr>
    <th>商品代金以外の必要料金</th>
    <td>消費税がかかります</td>
  </tr>
  <tr>
    <th>返品について</th>
    <td>
    【返品の可否】<br>
    初期不良・弊社手違い等合った場合は、商品到着後10日以内にご連絡を頂いた上で返金を受付けます。<br>また、原則としてお客様都合による返金はお受けできませんので、予めご了承下さい。<br><br>
    </td>
  </tr>
  <tr>
    <th>引き渡し時期</th>
    <td>即日<br>
　　  ご入金後、商品がダウンロードされた事をご確認ください。</td>
  </tr>
  <tr>
    <th>お支払方法</th>
    <td>カード決済<br>
    クレジットカード</td>
  </tr>
  <tr>
    <th>決済期間</th>
    <td>即日になります。</td>
  </tr>
  <tr>
    <th>配送について</th>
    <td>ダウンロードでの商品の取得になります。</td>
  </tr>
  <tr>
    <th>個人情報について</th>
    <td>お客様の個人情報を第三者に開示することはございません。</td>
  </tr>
  <tr>
    <th>値</th>
    <td>¥100</td>
  </tr>
</table>
<?php get_footer(); ?> 